insert into categories (id, name) values (1, 'Marlite Panels (FED)');
insert into categories (id, name) values (2, 'Roofing (Asphalt)');
insert into categories (id, name) values (3, 'Fire Protection');
insert into categories (id, name) values (4, 'Electrical and Fire Alarm');
insert into categories (id, name) values (5, 'Waterproofing & Caulking');
insert into categories (id, name) values (6, 'Glass & Glazing');
insert into categories (id, name) values (7, 'Rebar & Wire Mesh Install');
insert into categories (id, name) values (8, 'Framing (Steel)');
insert into categories (id, name) values (9, 'Masonry & Precast');
insert into categories (id, name) values (10, 'Temp Fencing, Decorative Fencing and Gates');
